### ISSUE TITLE
Hard-code styles into code

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/forumfmt#10]
Having styles is awesome, but I want to keep this utility as a single binary so I'd like to embed some of the styles into the binary.

I'll still provide the option to load custom styles via a JSON though.

Now there's a simple way and a difficult but maybe interesting way to do this:

1. Simply convert the JSON files to Go structs and add a .go file for each - syntax is very similar so people shouldn't have an issue creating their own styles.
2. Embed the JSON files at build time using resource embedding - I've not done this before so it might be a nice opportunity to learn something new! This allows the repo to keep JSON files which people can easily edit without knowing Go struct syntax.

**Comment by Y-Less** [comment]
You could just remove my style and put yours in the code as the default as it was before. Not totally sure why I even pushed my style. Keep the ability to load it obviously though.
