### ISSUE TITLE
Is there an online converter for this?

### ISSUE THREAD

**Issue by AmirSavand** [Southclaws/forumfmt#14]

**Comment by Y-Less** [comment]
http://forum.sa-mp.com/showthread.php?t=656108

**Comment by AmirSavand** [comment]
Thanks <3

**Comment by Southclaws** [comment]
Incidentally, I realised this app actually compiles to WebAssembly so it could actually be run in the browser!

**Comment by Y-Less** [comment]
Yes, then I can stop using AWS for my forum plugin.
